### ISSUE TITLE
yum管理太混乱

### ISSUE THREAD

**Issue by zbuse** [inpanel/inpanel#10]
例如epel-release可以直接yum install -y epel-release 安装
CentALT源链接不上
nginx和apache以及php管理衔接问题。
centos5已经停更，早就该移除了。
另外还有好多问题，作者还是原来的江？？？

**Comment by doudoudzj** [comment]
首先感谢使用并提出以上问题，这些问题将来会一一解决优化，如果觉得这些问题影响了使用，请 D.I.Y.
我不是原作者，VPSMate在2013年已经停止开发，原作者放弃VPSMate另外新开发一套管理面板，说明本面板还是存在缺陷的，现阶段最先处理的是对新功能的开发以及对严重bug的修复，然后将会对整个框架进行优化
