### ISSUE TITLE
后台无法访问

### ISSUE THREAD

**Issue by scvoet** [inpanel/inpanel#11]
操作系统：centos7 x64
服务商：vultr 新加坡
面板版本：Dev
安装后访问IP地址+8888端口失败

**Comment by scvoet** [comment]
抱歉，没有注意到仅支持5.X和6.X（原地自裁）希望能够尽快支持7.X

**Comment by scvoet** [comment]
在我切换到6 x64后仍无法访问

**Comment by doudoudzj** [comment]
> 在我切换到6 x64后仍无法访问

会不会是由于防火墙的原因啊

**Comment by doudoudzj** [comment]
> 在我切换到6 x64后仍无法访问

可以贴个图吗看下安装的过程，不知道面板是否安装成功呢？测试了几次，防火墙规则应该是没有问题的啊

**Comment by scvoet** [comment]
我已经重装了，但当时应该是安装成功了，已有提示出现。

**Comment by doudoudzj** [comment]
@scvoet 重装之后可以访问吗？安装成功的界面会有提示防火墙规则是否启动的，如下图看到的白色矩形框类似的内容，如果是别的提示，麻烦贴个图，我看下具体问题哈

![image](https://user-images.githubusercontent.com/9668839/55550953-344a0100-570c-11e9-8d82-d6b45e610202.png)

**Comment by scvoet** [comment]
> @scvoet 重装之后可以访问吗？安装成功的界面会有提示防火墙规则是否启动的，如下图看到的白色矩形框类似的内容，如果是别的提示，麻烦贴个图，我看下具体问题哈
> 
> ![image](https://user-images.githubusercontent.com/9668839/55550953-344a0100-570c-11e9-8d82-d6b45e610202.png)

我晚点重装试试看
