### ISSUE TITLE
Do not force the installation of python2

### ISSUE THREAD

**Issue by jksdou** [inpanel/inpanel#17]
Do not force the installation of python2. In the installation script, replace it with the default python of the system
默认使用系统自带的Python，系统未安装的默认安装最新版本的Python

**Comment by AtomRun-Code** [comment]
没怎么看懂大哥想说的是啥。反正我已经正在踩雷的路上。
系统：almalinux-8.4-x86_64
海外VPS，由于系统里没有python，然后`yum install python2`
后来把官方的安装命令改成了`python2 install.py`
用户名，密码和端口都设定好了。启动不成功，我是不是要换成python3.9?

**Comment by doudoudzj** [comment]
> 没怎么看懂大哥想说的是啥。反正我已经正在踩雷的路上。 系统：almalinux-8.4-x86_64
> 
> 海外VPS，由于系统里没有python，然后 `yum install python2` 后来把官方的安装命令改成了 `python2 install.py` 用户名，密码和端口都设定好了。启动不成功，我是不是要换成python3.9?
> 
> 通过 `systemctl status inpanel` 得到两行错误的提示，不知道是什么意思： Active: failed (Result: protocol) Failed to start SYSV: InPanel is a web-based linux VPS management tools.


抱歉，并么有针对 almalinux 系统进行适配处理。

尝试使用命令 `python2 server.py` 直接执行，查看是否能够正常运行

运行此命令 `systemctl status inpanel` 需要系统支持此服务，前提需要将文件 `scripts/init.d/centos/inpanel` 放置在 `/etc/init.d/` 内

**Comment by AtomRun-Code** [comment]
> > 没怎么看懂大哥想说的是啥。反正我已经正在踩雷的路上。 系统：almalinux-8.4-x86_64
> > 海外VPS，由于系统里没有python，然后 `yum install python2` 后来把官方的安装命令改成了 `python2 install.py` 用户名，密码和端口都设定好了。启动不成功，我是不是要换成python3.9?
> > 通过 `systemctl status inpanel` 得到两行错误的提示，不知道是什么意思： Active: failed (Result: protocol) Failed to start SYSV: InPanel is a web-based linux VPS management tools.
> 
> 抱歉，没有针对 almalinux 系统进行适配处理。
> 
> 请尝试使用命令 `python2 server.py` 直接执行，查看是否能够正常运行
> 
> 运行此命令 `systemctl status inpanel` 需要系统支持此服务，前提需要将文件 `scripts/init.d/centos/inpanel` 放置在 `/etc/init.d/` 内

谢谢你的回复，现在已经换成了Debian11（代号：Bullseye）。再试试，由于宝塔需要手机注册认证，真心希望inpanel可以借此机会发展起来。看过一些网上的介绍，简洁高效，真是维护人员的福音。

**Comment by doudoudzj** [comment]
> 

由于此面板【对软件的管理是基于系统自带的软件包管理模式】的限制，目前只支持 CentOS，加上 python 版本兼容问题，目前项目正在重构中（还是基于 python 语言）

计划分发单文件执行程序，从根本上解决版本问题（已完成），基础功能正在开发补充中，另外系统兼容功能还在探索中，当前具体开发进度可以在分支 1.2.0 查看。

如果您有更好的方案，可以进一步探讨。

**Comment by AtomRun-Code** [comment]
> 

努力学习中，希望有朝一日能为项目作出贡献。加油！
