### ISSUE TITLE
发现问题~时间设置&数据库

### ISSUE THREAD

**Issue by lovelivetw** [inpanel/inpanel#5]
1.
"系统" > "时间设置" > 进入后出现 发生未知错误！
"系统" > "时间设置" > "时间同步服务" > 正在检测NTPD服务状态... 没有结果

2.
"数据库" > 获取用户列表失败！

感謝doudoudzj大大

**Comment by doudoudzj** [comment]
时间同步问题已解决 @lovelivetw

**Comment by lovelivetw** [comment]
"系统" > "时间设置" > "时间同步服务" > 正在检测NTPD服务状态
CentOS Linux 7.5.1804 Core 正常
CentOS 6.10 Final 正常

"系统" > "时间设置" > 进入后
CentOS Linux 7.5.1804 Core 正常
CentOS 6.10 Final 发生未知错误！

在这里跟您回报~谢谢您的开发>M<

**Comment by doudoudzj** [comment]
> "系统" > "时间设置" > "时间同步服务" > 正在检测NTPD服务状态
> CentOS Linux 7.5.1804 Core 正常
> CentOS 6.10 Final 正常
> 
> "系统" > "时间设置" > 进入后
> CentOS Linux 7.5.1804 Core 正常
> CentOS 6.10 Final 发生未知错误！
> 
> 在这里跟您回报~谢谢您的开发>M<

好的，谢谢，我换个系统来找下问题
