### ISSUE TITLE
谢谢大佬开发的面板,希望支持更多系统

### ISSUE THREAD

**Issue by myqmdx** [inpanel/inpanel#6]
谢谢大佬开发的面板，很好用，希望支持更多的系统(Debian/Ubuntu) ！

**Comment by doudoudzj** [comment]
> 谢谢大佬开发的面板，很好用，希望支持更多的系统(Debian/Ubuntu) ！

谢谢使用，很多功能正在开发中，毕竟几年没更新了，现在流行的功能都在逐个跟进中，包括对多个系统（版本）的支持，尤其是Debian/Ubuntu

**Comment by myqmdx** [comment]
好的，谢谢大佬！
