### ISSUE TITLE
安装脚本上的防火墙放行无效

### ISSUE THREAD

**Issue by jiqing112** [inpanel/inpanel#7]
安装成功之后提示 firewall没有安装不需要配置，但是访问ip端口无响应，手动关闭firewall.service之后就可以访问到了，应该是安装脚本上的防火墙放行的判断不够准确。我不会py，没办法手动给改，只能提个issue

> Config firewall... Not Installed, No configuration required.
![snipaste_2019-02-28_13-26-50](https://user-images.githubusercontent.com/17674011/53543147-96877300-3b5c-11e9-91b1-e7e22f85bbed.png)

![snipaste_2019-02-28_13-27-02](https://user-images.githubusercontent.com/17674011/53543200-d189a680-3b5c-11e9-8412-16d778429fb2.png)
![snipaste_2019-02-28_13-29-30](https://user-images.githubusercontent.com/17674011/53543227-efefa200-3b5c-11e9-85b0-3758ce5a8e0e.png)

**Comment by doudoudzj** [comment]
@jiqing112 你好，CentOS 7 使用的防火墙是firewalld，面板暂时没有做支持，后面将做支持
